spring:
  application:
    name: ssmc-eureka
server:
  port: 8761
eureka.instance:
    hostname: localhost
    port: 8761
eureka.client:
  register-with-eureka: false
  fetch-registry: false
# 配置Eureka注册服务地址，默认端口为8761
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
